### ISSUE TITLE
[ITEM] Growstuff

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/newsletter#28]
Awesome open project http://growstuff.org/

**Comment by kat** [comment]
how about:

Growstuff is 'a community of food gardeners who are building an open source platform to help you learn about growing food, track what you plant and harvest, and swap seeds and produce with other gardeners near you.'

We love this one because It's a very practical open source project which helps people grow food, community. It's also helping keep information held in plants and seeds open by making it easy to share them. Growstuff is releasing all the data it collects with open licenses. It gives power to it’s community of developers as well as growing a community of gardeners. With developers it promotes pair programming as the norm, and if you’re a gardener you get to benefit from sharing your experiences, food and seeds. 

This is a very active project which is often looking for volunteers to help test, write for the [Growstuff blog](blog.growstuff.org) as well as [contribute code](https://github.com/growstuff), and of course you can just dig in, grow some food, share seeds, and data at www.growstuff.org

**Comment by equivalentideas** [comment]
Great, thanks @kat . Slight edit to trim some spare words:

> Growstuff is 'a community of food gardeners who are building an open source platform to help you learn about growing food, track what you plant and harvest, and swap seeds and produce with other gardeners near you.'
> 
> We love this one because It's a practical open source project helping people grow food and community. It helps keep information held in plants and seeds open by making it easy to share. Growstuff releases the data it collects under open licenses, giving power to it’s developers as well as growing a community of gardeners. It promotes pair programming as the norm.
> 
> This is a very active project. Get involved as a volunteer to help test or develop the application or just dig in, grow some food and share your seeds and data.

**Comment by kat** [comment]
thanks that's better. maybe just put the links back?

**Comment by equivalentideas** [comment]
Almost missed them, thanks :)
