### ISSUE TITLE
[ITEM] Right to Know Changes

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/newsletter#48]
Add bits about Right to Know now being Mobile Friendly and adding the ACT.

**Comment by equivalentideas** [comment]
Draft text:

## Right To Know is now in the ACT and on your phone!

This month we've been making big improvements to our Freedom of Information project, [Right To Know](https://www.righttoknow.org.au/). So far you’ve only been able to request information from the Federal Government but now you’re also able to [request information from the ACT Government using Right to Know](https://www.openaustraliafoundation.org.au/2015/04/13/right-to-know-is-now-in-the-act/). We've also made big changes to the design of the project so that it’s [much more useable from mobiles](https://www.openaustraliafoundation.org.au/2015/04/02/a-better-right-to-know-on-your-phone/). It should be much easier to read request exchanges and even make requests no matter what device you use.
